/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    companies: Company;
    'user-profiles': UserProfile;
    tags: Tag;
    categories: Category;
    instructors: Instructor;
    programs: Program;
    rounds: Round;
    sessions: Session;
    'payment-plans': PaymentPlan;
    bookings: Booking;
    payments: Payment;
    'installment-requests': InstallmentRequest;
    notifications: Notification;
    'discount-codes': DiscountCode;
    'consultation-types': ConsultationType;
    'consultation-availability': ConsultationAvailability;
    'consultation-slots': ConsultationSlot;
    'consultation-bookings': ConsultationBooking;
    leads: Lead;
    waitlist: Waitlist;
    reviews: Review;
    certificates: Certificate;
    'payment-links': PaymentLink;
    'instructor-blocked-dates': InstructorBlockedDate;
    'verification-codes': VerificationCode;
    'blog-posts': BlogPost;
    'bulk-seat-allocations': BulkSeatAllocation;
    popups: Popup;
    'announcement-bars': AnnouncementBar;
    'upcoming-events-config': UpcomingEventsConfig;
    'crm-sync-events': CrmSyncEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'user-profiles': UserProfilesSelect<false> | UserProfilesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    rounds: RoundsSelect<false> | RoundsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'payment-plans': PaymentPlansSelect<false> | PaymentPlansSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'installment-requests': InstallmentRequestsSelect<false> | InstallmentRequestsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    'consultation-types': ConsultationTypesSelect<false> | ConsultationTypesSelect<true>;
    'consultation-availability': ConsultationAvailabilitySelect<false> | ConsultationAvailabilitySelect<true>;
    'consultation-slots': ConsultationSlotsSelect<false> | ConsultationSlotsSelect<true>;
    'consultation-bookings': ConsultationBookingsSelect<false> | ConsultationBookingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    waitlist: WaitlistSelect<false> | WaitlistSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    'payment-links': PaymentLinksSelect<false> | PaymentLinksSelect<true>;
    'instructor-blocked-dates': InstructorBlockedDatesSelect<false> | InstructorBlockedDatesSelect<true>;
    'verification-codes': VerificationCodesSelect<false> | VerificationCodesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'bulk-seat-allocations': BulkSeatAllocationsSelect<false> | BulkSeatAllocationsSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
    'announcement-bars': AnnouncementBarsSelect<false> | AnnouncementBarsSelect<true>;
    'upcoming-events-config': UpcomingEventsConfigSelect<false> | UpcomingEventsConfigSelect<true>;
    'crm-sync-events': CrmSyncEventsSelect<false> | CrmSyncEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  gender?: ('male' | 'female') | null;
  picture?: (number | null) | Media;
  role: 'user' | 'admin' | 'instructor' | 'b2b_manager';
  instructorId?: (number | null) | Instructor;
  preferredLanguage?: ('ar' | 'en') | null;
  newsletterOptIn?: boolean | null;
  whatsappOptIn?: boolean | null;
  lifecycleStage?: ('lead' | 'prospect' | 'customer' | 'repeat') | null;
  contactSource?: ('website' | 'whatsapp' | 'social' | 'referral') | null;
  twentyCrmContactId?: string | null;
  /**
   * Google OAuth sub ID
   */
  googleId?: string | null;
  emailVerified?: boolean | null;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  firstName: string;
  lastName: string;
  slug: string;
  bioAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bioEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  jobTitle?: string | null;
  tagline?: string | null;
  picture?: (number | null) | Media;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  email?: string | null;
  featuredOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  industry?: string | null;
  size?: ('1-10' | '11-50' | '51-200' | '201-500' | '500+') | null;
  type?: ('startup' | 'sme' | 'enterprise' | 'government' | 'freelancer') | null;
  website?: string | null;
  country?: string | null;
  city?: string | null;
  logo?: (number | null) | Media;
  twentyCrmCompanyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profiles".
 */
export interface UserProfile {
  id: number;
  user: number | User;
  title?: ('Mr' | 'Mrs' | 'Dr' | 'Eng' | 'Prof') | null;
  jobTitle?: string | null;
  workField?: ('Marketing' | 'Sales' | 'Tech' | 'Finance' | 'Operations' | 'HR' | 'Legal' | 'Other') | null;
  yearsOfExperience?: ('0-2' | '3-5' | '6-10' | '10+') | null;
  education?: ('High School' | 'Bachelor' | 'Master' | 'MBA' | 'PhD' | 'Other') | null;
  yearOfBirth?: number | null;
  country?: string | null;
  city?: string | null;
  company?: (number | null) | Company;
  companySize?: ('1-10' | '11-50' | '51-200' | '201-500' | '500+') | null;
  companyType?: ('startup' | 'sme' | 'enterprise' | 'government' | 'freelancer') | null;
  linkedinUrl?: string | null;
  learningGoals?: string | null;
  interests?: (number | Tag)[] | null;
  howDidYouHear?: ('website' | 'whatsapp' | 'social' | 'friend' | 'google' | 'other') | null;
  onboardingCompleted?: boolean | null;
  onboardingStep?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  nameAr: string;
  nameEn?: string | null;
  slug: string;
  type: 'interest' | 'skill' | 'industry' | 'topic';
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nameAr: string;
  nameEn?: string | null;
  slug: string;
  descriptionAr?: string | null;
  descriptionEn?: string | null;
  icon?: string | null;
  parent?: (number | null) | Category;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  type: 'workshop' | 'course' | 'webinar';
  titleAr: string;
  titleEn?: string | null;
  slug: string;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescriptionAr?: string | null;
  shortDescriptionEn?: string | null;
  category?: (number | null) | Category;
  instructor?: (number | null) | Instructor;
  thumbnail?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  durationHours?: number | null;
  sessionsCount?: number | null;
  level?: ('beginner' | 'intermediate' | 'advanced') | null;
  language?: ('ar' | 'en' | 'both') | null;
  objectives?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  targetAudience?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?: (number | Tag)[] | null;
  isFeatured?: boolean | null;
  /**
   * Controls ordering in featured cards (lower appears first)
   */
  featuredPriority?: number | null;
  isActive?: boolean | null;
  learnersCount?: number | null;
  viewCount?: number | null;
  averageRating?: number | null;
  reviewCount?: number | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rounds".
 */
export interface Round {
  id: number;
  program: number | Program;
  /**
   * Round index inside the same program (1, 2, 3...). Create a separate Round record for each round.
   */
  roundNumber: number;
  title?: string | null;
  /**
   * Add one row per session. Each session has its own date/time, and round start/end dates are synced automatically.
   */
  sessionPlan?:
    | {
        title?: string | null;
        date: string;
        startTime: string;
        endTime: string;
        locationType?: ('online' | 'in-person' | 'hybrid') | null;
        locationName?: string | null;
        locationAddress?: string | null;
        meetingUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-synced from the earliest session date when Session Plan is filled.
   */
  startDate: string;
  /**
   * Auto-synced from the latest session date when Session Plan is filled.
   */
  endDate?: string | null;
  timezone?: string | null;
  locationType?: ('online' | 'in-person' | 'hybrid') | null;
  locationName?: string | null;
  locationAddress?: string | null;
  locationMapUrl?: string | null;
  meetingUrl?: string | null;
  maxCapacity: number;
  currentEnrollments?: number | null;
  price: number;
  earlyBirdPrice?: number | null;
  earlyBirdDeadline?: string | null;
  currency?: ('EGP' | 'USD' | 'EUR') | null;
  status?: ('draft' | 'upcoming' | 'open' | 'full' | 'in_progress' | 'cancelled' | 'completed') | null;
  isActive?: boolean | null;
  autoCloseOnFull?: boolean | null;
  reminderSent?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  round: number | Round;
  sessionNumber: number;
  title: string;
  description?: string | null;
  date: string;
  startTime: string;
  endTime: string;
  locationType?: ('online' | 'in-person' | 'hybrid') | null;
  locationName?: string | null;
  locationAddress?: string | null;
  meetingUrl?: string | null;
  instructor?: (number | null) | Instructor;
  recordingUrl?: string | null;
  materials?: (number | Media)[] | null;
  status?: ('scheduled' | 'live' | 'completed' | 'cancelled') | null;
  isCancelled?: boolean | null;
  cancellationReason?: string | null;
  attendanceCount?: number | null;
  attendeesCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-plans".
 */
export interface PaymentPlan {
  id: number;
  round: number | Round;
  name: string;
  nameEn?: string | null;
  installmentsCount: number;
  description?: string | null;
  installments: {
    installmentNumber: number;
    percentage: number;
    dueDaysFromBooking: number;
    description?: string | null;
    id?: string | null;
  }[];
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  bookingCode?: string | null;
  user: number | User;
  round: number | Round;
  paymentPlan?: (number | null) | PaymentPlan;
  installmentRequest?: (number | null) | InstallmentRequest;
  status:
    | 'reserved'
    | 'pending'
    | 'confirmed'
    | 'cancelled'
    | 'completed'
    | 'refunded'
    | 'payment_failed'
    | 'cancelled_overdue';
  totalAmount: number;
  paidAmount?: number | null;
  remainingAmount?: number | null;
  discountCode?: string | null;
  discountAmount?: number | null;
  finalAmount: number;
  accessBlocked?: boolean | null;
  bookingSource?: ('website' | 'whatsapp' | 'admin' | 'phone' | 'payment_link') | null;
  bookedByAdmin?: (number | null) | User;
  notes?: string | null;
  internalNotes?: string | null;
  twentyCrmDealId?: string | null;
  confirmationEmailSent?: boolean | null;
  reminderEmailSent?: boolean | null;
  cancelledAt?: string | null;
  cancellationReason?: string | null;
  refundAmount?: number | null;
  refundDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installment-requests".
 */
export interface InstallmentRequest {
  id: number;
  user: number | User;
  round: number | Round;
  paymentPlan: number | PaymentPlan;
  status: 'pending' | 'approved' | 'rejected' | 'expired';
  reason: string;
  nationalIdNumber?: string | null;
  nationalIdImage?: (number | null) | Media;
  userNotes?: string | null;
  adminNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  approvalExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  paymentCode?: string | null;
  booking: number | Booking;
  installmentNumber?: number | null;
  amount: number;
  dueDate: string;
  paidDate?: string | null;
  status: 'pending' | 'paid' | 'overdue' | 'failed' | 'refunded';
  paymentMethod?: ('paymob' | 'fawry' | 'cash' | 'bank_transfer' | 'voucher') | null;
  transactionId?: string | null;
  paymobOrderId?: string | null;
  paymentGatewayResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  receiptUrl?: string | null;
  receiptNumber?: string | null;
  notes?: string | null;
  reminderSentCount?: number | null;
  lastReminderSent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type:
    | 'booking_confirmed'
    | 'payment_reminder'
    | 'payment_received'
    | 'round_starting'
    | 'session_reminder'
    | 'booking_cancelled'
    | 'round_cancelled'
    | 'consultation_confirmed'
    | 'consultation_reminder'
    | 'installment_approved'
    | 'installment_rejected'
    | 'certificate_ready'
    | 'waitlist_available'
    | 'payment_overdue'
    | 'access_blocked'
    | 'refund_approved'
    | 'review_request';
  title: string;
  message: string;
  actionUrl?: string | null;
  isRead?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  maxUses?: number | null;
  currentUses?: number | null;
  validFrom: string;
  validUntil: string;
  applicableTo?: ('all' | 'specific_programs' | 'specific_categories' | 'consultations') | null;
  programs?: (number | Program)[] | null;
  categories?: (number | Category)[] | null;
  minPurchaseAmount?: number | null;
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-types".
 */
export interface ConsultationType {
  id: number;
  instructor: number | Instructor;
  titleAr: string;
  titleEn?: string | null;
  /**
   * Compatibility field used by frontend contract.
   */
  title?: string | null;
  descriptionAr?: string | null;
  descriptionEn?: string | null;
  /**
   * Compatibility field used by frontend contract.
   */
  description?: string | null;
  durationMinutes: number;
  price: number;
  currency?: ('EGP' | 'USD') | null;
  meetingType?: ('online' | 'in-person' | 'both') | null;
  meetingPlatform?: string | null;
  maxParticipants?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-availability".
 */
export interface ConsultationAvailability {
  id: number;
  instructor: number | Instructor;
  dayOfWeek: 'saturday' | 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday';
  /**
   * Compatibility numeric day index (0=Sunday ... 6=Saturday).
   */
  dayIndex?: number | null;
  startTime: string;
  endTime: string;
  bufferMinutes?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-slots".
 */
export interface ConsultationSlot {
  id: number;
  consultationType: number | ConsultationType;
  instructor: number | Instructor;
  date: string;
  startTime: string;
  endTime: string;
  status: 'available' | 'booked' | 'blocked' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-bookings".
 */
export interface ConsultationBooking {
  id: number;
  bookingCode?: string | null;
  user: number | User;
  slot: number | ConsultationSlot;
  consultationType: number | ConsultationType;
  instructor: number | Instructor;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  amount: number;
  paymentStatus?: ('pending' | 'paid' | 'refunded') | null;
  transactionId?: string | null;
  meetingUrl?: string | null;
  userNotes?: string | null;
  instructorNotes?: string | null;
  cancelledBy?: ('user' | 'instructor' | 'admin') | null;
  cancellationReason?: string | null;
  reminderSent?: boolean | null;
  discountCode?: string | null;
  discountAmount?: number | null;
  twentyCrmDealId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phone: string;
  company?: string | null;
  jobTitle?: string | null;
  source: 'whatsapp' | 'facebook' | 'instagram' | 'linkedin' | 'referral' | 'cold_call' | 'event' | 'other';
  sourceDetails?: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'nurturing' | 'converted' | 'lost';
  interestedIn?: (number | Program)[] | null;
  notes?: string | null;
  twentyCrmLeadId?: string | null;
  convertedUser?: (number | null) | User;
  convertedAt?: string | null;
  assignedTo?: (number | null) | User;
  lastContactDate?: string | null;
  nextFollowUpDate?: string | null;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  lostReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist".
 */
export interface Waitlist {
  id: number;
  user: number | User;
  round: number | Round;
  position: number;
  status: 'waiting' | 'notified' | 'expired' | 'converted';
  notifiedAt?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  user: number | User;
  program: number | Program;
  round: number | Round;
  booking: number | Booking;
  rating: number;
  title?: string | null;
  comment: string;
  status: 'pending' | 'approved' | 'flagged' | 'removed';
  helpfulCount?: number | null;
  isVerifiedPurchase?: boolean | null;
  adminNotes?: string | null;
  removedReason?: string | null;
  isVideoTestimonial?: boolean | null;
  videoUrl?: string | null;
  videoThumbnail?: (number | null) | Media;
  videoCaption?: string | null;
  videoSubtitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  certificateCode: string;
  user: number | User;
  program: number | Program;
  round: number | Round;
  booking: number | Booking;
  quizScore?: number | null;
  passingScore?: number | null;
  issuedAt: string;
  pdfUrl?: string | null;
  verificationUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-links".
 */
export interface PaymentLink {
  id: number;
  code: string;
  title: string;
  round: number | Round;
  paymentPlan?: (number | null) | PaymentPlan;
  discountCode?: string | null;
  expiresAt?: string | null;
  maxUses?: number | null;
  currentUses?: number | null;
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructor-blocked-dates".
 */
export interface InstructorBlockedDate {
  id: number;
  instructor: number | Instructor;
  date: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes".
 */
export interface VerificationCode {
  id: number;
  email: string;
  code: string;
  expiresAt: string;
  used?: boolean | null;
  type: 'email_verification' | 'password_reset';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g. "how-to-grow-your-business")
   */
  slug: string;
  /**
   * Short summary shown on blog listing cards
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('strategy' | 'leadership' | 'marketing' | 'technology' | 'finance' | 'hr' | 'general') | null;
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  tags?: (number | Tag)[] | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-seat-allocations".
 */
export interface BulkSeatAllocation {
  id: number;
  company: number | Company;
  round: number | Round;
  /**
   * Number of seats purchased for this round
   */
  totalSeats: number;
  status: 'active' | 'expired' | 'cancelled';
  allocations?:
    | {
        user: number | User;
        allocatedAt?: string | null;
        status: 'pending' | 'enrolled' | 'cancelled';
        id?: string | null;
      }[]
    | null;
  purchaseDate?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  name: string;
  status: 'draft' | 'active' | 'paused' | 'archived';
  content?: {
    titleAr?: string | null;
    titleEn?: string | null;
    badgeAr?: string | null;
    badgeEn?: string | null;
    subtitleAr?: string | null;
    subtitleEn?: string | null;
    descriptionAr?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    descriptionEn?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    legalNoteAr?: string | null;
    legalNoteEn?: string | null;
    image?: (number | null) | Media;
    imagePosition?: ('left' | 'right' | 'top' | 'none') | null;
  };
  cta?: {
    primaryCtaText?: string | null;
    primaryCtaLink?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaLink?: string | null;
  };
  promo?: {
    hasPromoCode?: boolean | null;
    promoCode?: string | null;
    promoDelivery?: ('show_directly' | 'after_form' | 'send_email') | null;
  };
  form?: {
    hasForm?: boolean | null;
    formFields?:
      | {
          fieldLabel: string;
          fieldType: 'email' | 'text' | 'phone' | 'name';
          isRequired?: boolean | null;
          id?: string | null;
        }[]
      | null;
    successMessage?: string | null;
    redirectUrl?: string | null;
  };
  appearance?: {
    stylePreset?: ('default' | 'offer_dark') | null;
    popupType?: ('modal' | 'slide_in' | 'bottom_bar' | 'full_screen') | null;
    animation?: ('fade' | 'slide_up' | 'slide_side' | 'zoom') | null;
    /**
     * Overlay opacity 0-100%
     */
    overlayDarkness?: number | null;
    closeOnOutsideClick?: boolean | null;
    bgColor?: string | null;
    textColor?: string | null;
    accentColor?: string | null;
    backgroundImage?: (number | null) | Media;
    /**
     * Background image dark overlay opacity 0-100%
     */
    backgroundOverlayOpacity?: number | null;
    borderColor?: string | null;
    badgeBgColor?: string | null;
    badgeTextColor?: string | null;
  };
  countdown?: {
    hasCountdown?: boolean | null;
    countdownTarget?: string | null;
  };
  targeting?: {
    displayPages?: ('all' | 'specific') | null;
    specificPages?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    triggerType?: ('on_load' | 'after_delay' | 'on_exit' | 'on_scroll') | null;
    /**
     * Seconds
     */
    triggerDelay?: number | null;
    /**
     * Scroll percentage
     */
    triggerScroll?: number | null;
    frequency?: ('every_time' | 'once_session' | 'once_day' | 'once_ever') | null;
    targetAudience?: ('all' | 'guests_only' | 'logged_in' | 'specific_role') | null;
    targetRole?: ('student' | 'instructor' | 'b2b_manager') | null;
    targetDevice?: ('all' | 'mobile' | 'desktop') | null;
    /**
     * Target first-time visitors or only returning visitors.
     */
    visitorCondition?: ('all' | 'first_visit' | 'returning_visitor') | null;
    /**
     * Use this to target users who purchased or not yet purchased.
     */
    purchaseCondition?: ('all' | 'no_purchase' | 'has_purchase') | null;
    /**
     * Email capture is tracked client-side when popup forms are submitted.
     */
    emailCaptureCondition?: ('all' | 'email_captured' | 'email_not_captured') | null;
    /**
     * Minimum pages viewed in the current session before this popup can appear.
     */
    minSessionPageViews?: number | null;
  };
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Higher = shows first
   */
  priority?: number | null;
  viewCount?: number | null;
  clickCount?: number | null;
  conversionCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bars".
 */
export interface AnnouncementBar {
  id: number;
  name: string;
  status: 'draft' | 'active' | 'paused';
  messages: {
    textAr: string;
    textEn: string;
    linkUrl?: string | null;
    /**
     * Emoji or icon name
     */
    icon?: string | null;
    id?: string | null;
  }[];
  appearance?: {
    position?: ('top' | 'bottom') | null;
    bgColor?: string | null;
    /**
     * Optional CSS gradient (overrides bgColor)
     */
    bgGradient?: string | null;
    textColor?: string | null;
    fontSize?: ('sm' | 'md' | 'lg') | null;
  };
  animation?: {
    isAnimated?: boolean | null;
    animationSpeed?: ('slow' | 'normal' | 'fast') | null;
    animationDirection?: ('ltr' | 'rtl') | null;
  };
  ctaButton?: {
    hasCtaButton?: boolean | null;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  countdown?: {
    hasCountdown?: boolean | null;
    countdownTarget?: string | null;
  };
  behavior?: {
    isDismissible?: boolean | null;
    /**
     * Remember dismiss via localStorage
     */
    rememberDismiss?: boolean | null;
  };
  targeting?: {
    displayPages?: ('all' | 'specific') | null;
    specificPages?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Higher = shows first
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-events-config".
 */
export interface UpcomingEventsConfig {
  id: number;
  isEnabled?: boolean | null;
  sectionTitleAr?: string | null;
  sectionTitleEn?: string | null;
  mode?: ('automatic' | 'manual') | null;
  filterType?: ('all' | 'workshop' | 'course' | 'webinar') | null;
  maxItems?: number | null;
  sortOrder?: ('date_asc' | 'manual') | null;
  /**
   * Auto-play interval in ms (0 = disabled)
   */
  autoPlaySpeed?: number | null;
  cardDisplay?: {
    showPrice?: boolean | null;
    showDate?: boolean | null;
    showInstructor?: boolean | null;
    showLocation?: boolean | null;
  };
  /**
   * URL for "View All" button
   */
  viewAllLink?: string | null;
  emptyMessageAr?: string | null;
  emptyMessageEn?: string | null;
  manualItems?:
    | {
        program: number | Program;
        round?: (number | null) | Round;
        customImage?: (number | null) | Media;
        customUrl?: string | null;
        /**
         * Lower = shows first
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-sync-events".
 */
export interface CrmSyncEvent {
  id: number;
  entityType:
    | 'user'
    | 'user_profile'
    | 'lead'
    | 'company'
    | 'booking'
    | 'payment'
    | 'consultation_booking'
    | 'bulk_seat_allocation'
    | 'waitlist';
  entityId: string;
  action: string;
  dedupeKey: string;
  status: 'pending' | 'processing' | 'done' | 'failed' | 'dead_letter';
  priority?: number | null;
  attempts?: number | null;
  nextRetryAt?: string | null;
  lastError?: string | null;
  payloadSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resultSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceCollection?: string | null;
  lockedAt?: string | null;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'user-profiles';
        value: number | UserProfile;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'rounds';
        value: number | Round;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'payment-plans';
        value: number | PaymentPlan;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'installment-requests';
        value: number | InstallmentRequest;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'consultation-types';
        value: number | ConsultationType;
      } | null)
    | ({
        relationTo: 'consultation-availability';
        value: number | ConsultationAvailability;
      } | null)
    | ({
        relationTo: 'consultation-slots';
        value: number | ConsultationSlot;
      } | null)
    | ({
        relationTo: 'consultation-bookings';
        value: number | ConsultationBooking;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'waitlist';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'payment-links';
        value: number | PaymentLink;
      } | null)
    | ({
        relationTo: 'instructor-blocked-dates';
        value: number | InstructorBlockedDate;
      } | null)
    | ({
        relationTo: 'verification-codes';
        value: number | VerificationCode;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'bulk-seat-allocations';
        value: number | BulkSeatAllocation;
      } | null)
    | ({
        relationTo: 'popups';
        value: number | Popup;
      } | null)
    | ({
        relationTo: 'announcement-bars';
        value: number | AnnouncementBar;
      } | null)
    | ({
        relationTo: 'upcoming-events-config';
        value: number | UpcomingEventsConfig;
      } | null)
    | ({
        relationTo: 'crm-sync-events';
        value: number | CrmSyncEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  gender?: T;
  picture?: T;
  role?: T;
  instructorId?: T;
  preferredLanguage?: T;
  newsletterOptIn?: T;
  whatsappOptIn?: T;
  lifecycleStage?: T;
  contactSource?: T;
  twentyCrmContactId?: T;
  googleId?: T;
  emailVerified?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  industry?: T;
  size?: T;
  type?: T;
  website?: T;
  country?: T;
  city?: T;
  logo?: T;
  twentyCrmCompanyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profiles_select".
 */
export interface UserProfilesSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  jobTitle?: T;
  workField?: T;
  yearsOfExperience?: T;
  education?: T;
  yearOfBirth?: T;
  country?: T;
  city?: T;
  company?: T;
  companySize?: T;
  companyType?: T;
  linkedinUrl?: T;
  learningGoals?: T;
  interests?: T;
  howDidYouHear?: T;
  onboardingCompleted?: T;
  onboardingStep?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  nameAr?: T;
  nameEn?: T;
  slug?: T;
  type?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nameAr?: T;
  nameEn?: T;
  slug?: T;
  descriptionAr?: T;
  descriptionEn?: T;
  icon?: T;
  parent?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  slug?: T;
  bioAr?: T;
  bioEn?: T;
  jobTitle?: T;
  tagline?: T;
  picture?: T;
  linkedinUrl?: T;
  twitterUrl?: T;
  email?: T;
  featuredOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  type?: T;
  titleAr?: T;
  titleEn?: T;
  slug?: T;
  descriptionAr?: T;
  descriptionEn?: T;
  shortDescriptionAr?: T;
  shortDescriptionEn?: T;
  category?: T;
  instructor?: T;
  thumbnail?: T;
  coverImage?: T;
  durationHours?: T;
  sessionsCount?: T;
  level?: T;
  language?: T;
  objectives?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  targetAudience?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tags?: T;
  isFeatured?: T;
  featuredPriority?: T;
  isActive?: T;
  learnersCount?: T;
  viewCount?: T;
  averageRating?: T;
  reviewCount?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rounds_select".
 */
export interface RoundsSelect<T extends boolean = true> {
  program?: T;
  roundNumber?: T;
  title?: T;
  sessionPlan?:
    | T
    | {
        title?: T;
        date?: T;
        startTime?: T;
        endTime?: T;
        locationType?: T;
        locationName?: T;
        locationAddress?: T;
        meetingUrl?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  timezone?: T;
  locationType?: T;
  locationName?: T;
  locationAddress?: T;
  locationMapUrl?: T;
  meetingUrl?: T;
  maxCapacity?: T;
  currentEnrollments?: T;
  price?: T;
  earlyBirdPrice?: T;
  earlyBirdDeadline?: T;
  currency?: T;
  status?: T;
  isActive?: T;
  autoCloseOnFull?: T;
  reminderSent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  round?: T;
  sessionNumber?: T;
  title?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  locationType?: T;
  locationName?: T;
  locationAddress?: T;
  meetingUrl?: T;
  instructor?: T;
  recordingUrl?: T;
  materials?: T;
  status?: T;
  isCancelled?: T;
  cancellationReason?: T;
  attendanceCount?: T;
  attendeesCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-plans_select".
 */
export interface PaymentPlansSelect<T extends boolean = true> {
  round?: T;
  name?: T;
  nameEn?: T;
  installmentsCount?: T;
  description?: T;
  installments?:
    | T
    | {
        installmentNumber?: T;
        percentage?: T;
        dueDaysFromBooking?: T;
        description?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingCode?: T;
  user?: T;
  round?: T;
  paymentPlan?: T;
  installmentRequest?: T;
  status?: T;
  totalAmount?: T;
  paidAmount?: T;
  remainingAmount?: T;
  discountCode?: T;
  discountAmount?: T;
  finalAmount?: T;
  accessBlocked?: T;
  bookingSource?: T;
  bookedByAdmin?: T;
  notes?: T;
  internalNotes?: T;
  twentyCrmDealId?: T;
  confirmationEmailSent?: T;
  reminderEmailSent?: T;
  cancelledAt?: T;
  cancellationReason?: T;
  refundAmount?: T;
  refundDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  paymentCode?: T;
  booking?: T;
  installmentNumber?: T;
  amount?: T;
  dueDate?: T;
  paidDate?: T;
  status?: T;
  paymentMethod?: T;
  transactionId?: T;
  paymobOrderId?: T;
  paymentGatewayResponse?: T;
  receiptUrl?: T;
  receiptNumber?: T;
  notes?: T;
  reminderSentCount?: T;
  lastReminderSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installment-requests_select".
 */
export interface InstallmentRequestsSelect<T extends boolean = true> {
  user?: T;
  round?: T;
  paymentPlan?: T;
  status?: T;
  reason?: T;
  nationalIdNumber?: T;
  nationalIdImage?: T;
  userNotes?: T;
  adminNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  approvalExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  actionUrl?: T;
  isRead?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  maxUses?: T;
  currentUses?: T;
  validFrom?: T;
  validUntil?: T;
  applicableTo?: T;
  programs?: T;
  categories?: T;
  minPurchaseAmount?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-types_select".
 */
export interface ConsultationTypesSelect<T extends boolean = true> {
  instructor?: T;
  titleAr?: T;
  titleEn?: T;
  title?: T;
  descriptionAr?: T;
  descriptionEn?: T;
  description?: T;
  durationMinutes?: T;
  price?: T;
  currency?: T;
  meetingType?: T;
  meetingPlatform?: T;
  maxParticipants?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-availability_select".
 */
export interface ConsultationAvailabilitySelect<T extends boolean = true> {
  instructor?: T;
  dayOfWeek?: T;
  dayIndex?: T;
  startTime?: T;
  endTime?: T;
  bufferMinutes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-slots_select".
 */
export interface ConsultationSlotsSelect<T extends boolean = true> {
  consultationType?: T;
  instructor?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-bookings_select".
 */
export interface ConsultationBookingsSelect<T extends boolean = true> {
  bookingCode?: T;
  user?: T;
  slot?: T;
  consultationType?: T;
  instructor?: T;
  status?: T;
  amount?: T;
  paymentStatus?: T;
  transactionId?: T;
  meetingUrl?: T;
  userNotes?: T;
  instructorNotes?: T;
  cancelledBy?: T;
  cancellationReason?: T;
  reminderSent?: T;
  discountCode?: T;
  discountAmount?: T;
  twentyCrmDealId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  jobTitle?: T;
  source?: T;
  sourceDetails?: T;
  status?: T;
  interestedIn?: T;
  notes?: T;
  twentyCrmLeadId?: T;
  convertedUser?: T;
  convertedAt?: T;
  assignedTo?: T;
  lastContactDate?: T;
  nextFollowUpDate?: T;
  priority?: T;
  lostReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist_select".
 */
export interface WaitlistSelect<T extends boolean = true> {
  user?: T;
  round?: T;
  position?: T;
  status?: T;
  notifiedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  program?: T;
  round?: T;
  booking?: T;
  rating?: T;
  title?: T;
  comment?: T;
  status?: T;
  helpfulCount?: T;
  isVerifiedPurchase?: T;
  adminNotes?: T;
  removedReason?: T;
  isVideoTestimonial?: T;
  videoUrl?: T;
  videoThumbnail?: T;
  videoCaption?: T;
  videoSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  certificateCode?: T;
  user?: T;
  program?: T;
  round?: T;
  booking?: T;
  quizScore?: T;
  passingScore?: T;
  issuedAt?: T;
  pdfUrl?: T;
  verificationUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-links_select".
 */
export interface PaymentLinksSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  round?: T;
  paymentPlan?: T;
  discountCode?: T;
  expiresAt?: T;
  maxUses?: T;
  currentUses?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructor-blocked-dates_select".
 */
export interface InstructorBlockedDatesSelect<T extends boolean = true> {
  instructor?: T;
  date?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes_select".
 */
export interface VerificationCodesSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  expiresAt?: T;
  used?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  featuredImage?: T;
  author?: T;
  tags?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-seat-allocations_select".
 */
export interface BulkSeatAllocationsSelect<T extends boolean = true> {
  company?: T;
  round?: T;
  totalSeats?: T;
  status?: T;
  allocations?:
    | T
    | {
        user?: T;
        allocatedAt?: T;
        status?: T;
        id?: T;
      };
  purchaseDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  content?:
    | T
    | {
        titleAr?: T;
        titleEn?: T;
        badgeAr?: T;
        badgeEn?: T;
        subtitleAr?: T;
        subtitleEn?: T;
        descriptionAr?: T;
        descriptionEn?: T;
        legalNoteAr?: T;
        legalNoteEn?: T;
        image?: T;
        imagePosition?: T;
      };
  cta?:
    | T
    | {
        primaryCtaText?: T;
        primaryCtaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
      };
  promo?:
    | T
    | {
        hasPromoCode?: T;
        promoCode?: T;
        promoDelivery?: T;
      };
  form?:
    | T
    | {
        hasForm?: T;
        formFields?:
          | T
          | {
              fieldLabel?: T;
              fieldType?: T;
              isRequired?: T;
              id?: T;
            };
        successMessage?: T;
        redirectUrl?: T;
      };
  appearance?:
    | T
    | {
        stylePreset?: T;
        popupType?: T;
        animation?: T;
        overlayDarkness?: T;
        closeOnOutsideClick?: T;
        bgColor?: T;
        textColor?: T;
        accentColor?: T;
        backgroundImage?: T;
        backgroundOverlayOpacity?: T;
        borderColor?: T;
        badgeBgColor?: T;
        badgeTextColor?: T;
      };
  countdown?:
    | T
    | {
        hasCountdown?: T;
        countdownTarget?: T;
      };
  targeting?:
    | T
    | {
        displayPages?: T;
        specificPages?:
          | T
          | {
              url?: T;
              id?: T;
            };
        triggerType?: T;
        triggerDelay?: T;
        triggerScroll?: T;
        frequency?: T;
        targetAudience?: T;
        targetRole?: T;
        targetDevice?: T;
        visitorCondition?: T;
        purchaseCondition?: T;
        emailCaptureCondition?: T;
        minSessionPageViews?: T;
      };
  startDate?: T;
  endDate?: T;
  priority?: T;
  viewCount?: T;
  clickCount?: T;
  conversionCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bars_select".
 */
export interface AnnouncementBarsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  messages?:
    | T
    | {
        textAr?: T;
        textEn?: T;
        linkUrl?: T;
        icon?: T;
        id?: T;
      };
  appearance?:
    | T
    | {
        position?: T;
        bgColor?: T;
        bgGradient?: T;
        textColor?: T;
        fontSize?: T;
      };
  animation?:
    | T
    | {
        isAnimated?: T;
        animationSpeed?: T;
        animationDirection?: T;
      };
  ctaButton?:
    | T
    | {
        hasCtaButton?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  countdown?:
    | T
    | {
        hasCountdown?: T;
        countdownTarget?: T;
      };
  behavior?:
    | T
    | {
        isDismissible?: T;
        rememberDismiss?: T;
      };
  targeting?:
    | T
    | {
        displayPages?: T;
        specificPages?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  startDate?: T;
  endDate?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-events-config_select".
 */
export interface UpcomingEventsConfigSelect<T extends boolean = true> {
  isEnabled?: T;
  sectionTitleAr?: T;
  sectionTitleEn?: T;
  mode?: T;
  filterType?: T;
  maxItems?: T;
  sortOrder?: T;
  autoPlaySpeed?: T;
  cardDisplay?:
    | T
    | {
        showPrice?: T;
        showDate?: T;
        showInstructor?: T;
        showLocation?: T;
      };
  viewAllLink?: T;
  emptyMessageAr?: T;
  emptyMessageEn?: T;
  manualItems?:
    | T
    | {
        program?: T;
        round?: T;
        customImage?: T;
        customUrl?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-sync-events_select".
 */
export interface CrmSyncEventsSelect<T extends boolean = true> {
  entityType?: T;
  entityId?: T;
  action?: T;
  dedupeKey?: T;
  status?: T;
  priority?: T;
  attempts?: T;
  nextRetryAt?: T;
  lastError?: T;
  payloadSnapshot?: T;
  resultSnapshot?: T;
  sourceCollection?: T;
  lockedAt?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}